### ISSUE TITLE
关于授权

### ISSUE THREAD

**Issue by jihchao** [zhen8838/AnimeStylized#15]
这是一个超级棒的项目。感谢~
这个项目的license是什么？需要商业授权吗？

**Comment by zhen8838** [comment]
谢谢您的夸奖, 这个项目暂时没有添加license,您可以直接使用.

**Comment by jihchao** [comment]
> 谢谢您的夸奖, 这个项目暂时没有添加license,您可以直接使用.

感谢，特别是dataset这部分的说明。
