### ISSUE TITLE
A possible bug in Whitenbox-GAN implementation

### ISSUE THREAD

**Issue by yushuinanrong** [zhen8838/AnimeStylized#9]
https://github.com/zhen8838/AnimeStylized/blob/e65d33d9d4e04256c120b4fe8d4f16d8255dcbdf/networks/gan/whiteboxnet.py#L19

I think this line should be changed to :
'''
x = self.conv1(self.leaky_relu(self.conv(inputs)))
'''

**Comment by zhen8838** [comment]
🤣you are right
